### ISSUE TITLE
اضافه کردن تبلیغات بنر

### ISSUE THREAD

**Issue by AHesami8** [DexterFstone/godot-adivery#1]
بنر ها راه مهمی برای تبلیغات هستند که در نسخه قبل این پلاگین ساپورت میشدند.
لطفا اضافه کردن تبلیغات بنری را در اولویت قرار دهید.
منتظر هستیم. با تشکر 🙂
در ضمن کار با بنر در نسخه قبلی کمی گیج کننده بود.

**Comment by DexterFstone** [comment]
این مورد درحال بررسی هستم تا به بهترین حالت ممکن پیاده سازی شود

**Comment by AHesami8** [comment]
دم شما گرم.اجرت با حضرت علی علیه السلام.
عیدت مبارک
