### ISSUE TITLE
تناقض بین مقاله آموزشی و آخرین نسخه

### ISSUE THREAD

**Issue by AHesami8** [DexterFstone/godot-adivery#4]
مطالب موجود در مقاله آموزشی موجود در `git hub`  مربوط به نسخه متفاوتی از افزونه است.
به عنوان مثال در نسخه فعلی (3.422.465) فقط یک کلاس `Advertisement` داریم  ولی در مقاله به سه کلاس اشاره میکند و استفاده از کلاس ادورتایزمنت را منع میکند.
احتمالا فراموش کردید ریپازتوری را آپدیت کنید؟🙂
با تشکر

**Comment by DexterFstone** [comment]
> مطالب موجود در مقاله آموزشی موجود در `git hub` مربوط به نسخه متفاوتی از افزونه است. به عنوان مثال در نسخه فعلی (3.422.465) فقط یک کلاس `Advertisement` داریم ولی در مقاله به سه کلاس اشاره میکند و استفاده از کلاس ادورتایزمنت را منع میکند. احتمالا فراموش کردید ریپازتوری را آپدیت کنید؟🙂 با تشکر

آموزش مربوطه درحال بروزرسانی هست و باید ابتدا بررسی شود و بعد کامیت میشود، نسخه فعلی ک شما دارید یک ویدیو آموزشی دارد که در یوتیوب موجود می باشد

**Comment by DexterFstone** [comment]
نسخه جدید قرار داده شد
